apiVersion: v1
kind: Secret
metadata:
  name: scraper-secret
type: Opaque
stringData:
  # temporal use of .Values to provide api-key from cmdline
  # better stored in encrypted secret
  SCRAPER_AUTH_KEY: {{ .Values.scraper.apiKey }}